name: sample_arch
description: Example Application to show arch sample.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_redux: ^0.5.2
  flutter_redux_navigation: ^0.3.1

  rxdart: ^0.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
